Repository Prowlarr/Indexers, pull requests merged in 2021-12, with the labels that each got.

#76 fix(hebits): enhancements and fixes
  definitions/v3/hebits.yml
Labels: Status: Ready for Review

#75 feat: add fuzer tracker
  definitions/v3/fuzer.yml
Labels: Status: Ready for Review

#51 Create bjshare.yml
  definitions/v2/bjshare.yml
Labels: Status: Ready for Review

#90 New: Baibako AllowRawSearch
  definitions/v3/baibako.yml
Labels: Status: Ready for Review

#89 jackett indexers as of 14a7ad37cbb948d0398a6e009bdf78295c6f756b [ygg]
  definitions/v2/yggcookie.yml
  definitions/v3/yggcookie.yml
Labels: Status: Ready for Review

#94 update linkomanija keyword search
  definitions/v2/linkomanija.yml
Labels: Status: Testing Needed, Status: Waiting for OP

#99 fix: add episode to search when using imdbid search
  definitions/v3/hebits.yml
Labels: Status: Waiting for OP
